### ISSUE TITLE
Split data file into two files: "Incomplete Data" and "Complete Data"

### ISSUE THREAD

**Issue by NIACCInnovWork** [NIACCInnovWork/Workspace-Login-V1#1]
**Current:**
The program saves login data out as a single file with a section for "Incomplete Data" and "Complete Data."  This was developed to capture incomplete data when the application closed unexpectedly and minimize the number of files created.  However, this file format requires that the text file be "cleaned" before being brought into excel for analysis.

**Requested:**
Write the data to two different files, one for completed data and one for incompleted data with appropriate files names to distinguish between the two.  This will allow for the workspace coordinator to manually handle incompleted data when needed while not disrupting the process of data analysis on a regular basis.

**Comment by rws-visuals** [comment]
Decided that one excel sheet would be fine. Probably will be using Python to export data.
