### ISSUE TITLE
Append Data to an Exisiting File

### ISSUE THREAD

**Issue by NIACCInnovWork** [NIACCInnovWork/Workspace-Login-V1#3]
*Current:*
The application currently generates a new file every time the save button is clicked or the application closes with unsaved data.  There is a check in place that prevents the creation of a new file if there is no data to be written, but this still generates a large number of files, some of which overlap in data, making for more time consuming data analysis.  The analysis conducted recently involved 9 different files after the test data, empty files, and redundant files were removed. Importing and consolidating this data is slow and cumbersome. 

*Requested:*
Implement a way for the application to append new data onto existing files to reduce the overall number of files used.  Ideally, create one new file per month, so that we aren't re-importing all the data each time and can instead import and analyze the data once a month.

**Comment by rws-visuals** [comment]
Implemented in a way where files saved from the program can be imported perfectly into excel. Unfortunately, mass importing is not yet possibly, but is being worked on. This effectively solves this issue, as I believe having a text file for each day is an effective means of keeping track of days and I am therefore closing this issue.
